//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int UsuID { get; set; }
        public string UsuNombre { get; set; }
        public string UsuPass { get; set; }
    }
}
